### PR TITLE
[HIVE]Support read hadoop/hive conf from system environment

### PR DESCRIPTION
**Pull request by hehuiyuan**
### Purpose

Support read hadoop/hive conf from system environment

### CODE REVIEW

**Comment by hehuiyuan** [comment]
Hi @JingsongLi  , take a look when you have time.

**Comment by Alibaba-HZY** [comment]
> Hi @JingsongLi , take a look when you have time.

i think you need to add doc describing the conf  loading order,and test for it

**Comment by JingsongLi** [comment]
Testing triggered.

**Comment by hehuiyuan** [comment]
> Testing triggered.

Add some test case.

**Comment by hehuiyuan** [comment]
Testing triggered.

**Comment by hehuiyuan** [comment]
> Testing triggered.

Add some test case.

**Comment by hehuiyuan** [comment]
There are some paimon-spark-common error. Try to merge master to current branch.

**Comment by hehuiyuan** [comment]
Testing triggered.

**Comment by hehuiyuan** [comment]
doc error

**Comment by hehuiyuan** [comment]
Testing triggered.

**Comment by hehuiyuan** [comment]
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.319 s <<< FAILURE! - in org.apache.paimon.docs.configuration.ConfigOptionsDocsCompletenessITCase
Error:  org.apache.paimon.docs.configuration.ConfigOptionsDocsCompletenessITCase.testCompleteness  Time elapsed: 0.298 s  <<< FAILURE!
java.lang.AssertionError: 
Documentation is outdated, please regenerate it according to the instructions in paimon-docs/README.md.
	Problems:
		Documentation of hadoop-conf-dir in HiveCatalogOptions is outdated. Expected: default=((none)) description=(File directory of the core-site.xml、hdfs-site.xml、yarn-site.xml、mapred-site.xml. Currently, only local file system paths are supported.
If not configured, try to load from 'HADOOP_CONF_DIR' or 'HADOOP_HOME' system environment.
Configure Priority: 1.from 'hadoop-conf-dir' 2.from HADOOP_CONF_DIR  3.from HADOOP_HOME/conf 4.HADOOP_HOME/etc/hadoop.).
		Documentation of hive-conf-dir in HiveCatalogOptions is outdated. Expected: default=((none)) description=(File directory of the hive-site.xml , used to create HiveMetastoreClient and security authentication, such as Kerberos, LDAP, Ranger and so on.
If not configured, try to load from 'HIVE_CONF_DIR' env.).
		Documented option hadoop-conf-dir does not exist.
		Documented option hive-conf-dir does not exist.

**Comment by hehuiyuan** [comment]
Testing triggered.

**Comment by hehuiyuan** [comment]
Hi @JingsongLi  ,would you  trigger test?

**Review by JingsongLi — APPROVED** [review]
+1

**Comment by hehuiyuan** [comment]
Hi @JingsongLi , the test class

> Hi @JingsongLi ,
> 
> ```java
> Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.319 s <<< FAILURE! - in org.apache.paimon.docs.configuration.ConfigOptionsDocsCompletenessITCase
> Error:  org.apache.paimon.docs.configuration.ConfigOptionsDocsCompletenessITCase.testCompleteness  Time elapsed: 0.298 s  <<< FAILURE!
> java.lang.AssertionError: 
> Documentation is outdated, please regenerate it according to the instructions in paimon-docs/README.md.
> 	Problems:
> 		Documentation of hadoop-conf-dir in HiveCatalogOptions is outdated. Expected: default=((none)) description=(File directory of the core-site.xml、hdfs-site.xml、yarn-site.xml、mapred-site.xml. Currently, only local file system paths are supported.
> If not configured, try to load from 'HADOOP_CONF_DIR' or 'HADOOP_HOME' system environment.
> Configure Priority: 1.from 'hadoop-conf-dir' 2.from HADOOP_CONF_DIR  3.from HADOOP_HOME/conf 4.HADOOP_HOME/etc/hadoop.).
> 		Documentation of hive-conf-dir in HiveCatalogOptions is outdated. Expected: default=((none)) description=(File directory of the hive-site.xml , used to create HiveMetastoreClient and security authentication, such as Kerberos, LDAP, Ranger and so on.
> If not configured, try to load from 'HIVE_CONF_DIR' env.).
> 		Documented option hadoop-conf-dir does not exist.
> 		Documented option hive-conf-dir does not exist.
> ```
> 
> The error has ambiguity, when both document and ConfigOption exist, but the description or default value are not same.
> 
> ```
> Documented option hadoop-conf-dir does not exist.
>     Documented option hive-conf-dir does not exist.
> ```
> 
> Is it feasible to add the following code?
> 
> ConfigOptionsDocsCompletenessITCase.compareDocumentedAndExistingOptions image
> 
> Test result: image


Hi @JingsongLi , does this need further improment?

**Pull request merged**
