### PR TITLE
[Feature] Improve ci trigger and cancel

### LINKED ISSUE #951: [Feature] Improve ci trigger and cancel
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

1. Multiple commits of the same PR require cancellation of the previous testings
2. The master merged commits cannot cancel the previous testing

But #883 broke the requirement ②.

### Solution

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by liugddx**
*(Please specify the module before the PR name: [core] ... or [flink] ...)*

### Purpose

close #951 

### Tests

*(List UT and IT cases to verify this change)*

### API and Format 

*(Does this change affect API or storage format)*

### Documentation

*(Does this change introduce a new feature)*

### CODE REVIEW

**Comment by liugddx** [comment]
image

Multiple commits of the same PR require cancellation of the previous testings is ok.

**Comment by liugddx** [comment]
@tisonkun @JingsongLi PTAL thanks.

**Review by tisonkun — APPROVED** [review]

**Review by JingsongLi — APPROVED** [review]
Looks good to me!

**Comment by liugddx** [comment]
image

It is worked.

**Pull request merged**
