### PR TITLE
[core] Replace table_store with paimon in docs and classes

### PR DESCRIPTION
**Pull request by FangYongs**
*(Please specify the module before the PR name: [core] ... or [flink] ...)*

### Purpose

This PR aims to replace keyword `table_store` with `paimon` in the project

### Tests

NO

### API and Format 

NO

### Documentation

NO

### CODE REVIEW

**Comment by JingsongLi** [comment]
We can merge https://github.com/apache/incubator-paimon/pull/642 first, WDYT?

**Comment by FangYongs** [comment]
> We can merge #642 first, WDYT?

Sound good to me

**Comment by JingsongLi** [comment]
> 

Let's rebase master.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
