### PR TITLE
[Flink]Support flink migrate hive database

### PR DESCRIPTION
**Pull request by TaoZex**
### Purpose

Support flink migrate hive database

### Tests

MigrateDatabaseProcedureITCase

### Documentation

migration-from-hive.md

### CODE REVIEW

**Comment by TaoZex** [comment]
PTAL @leaves12138

**Comment by TaoZex** [comment]
I have fixed ci. Please rerun it. Thanks. @leaves12138

**Review by leaves12138 — APPROVED** [review]
+1

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
