### PR TITLE
[core]CI execution optimization

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
### Purpose

-T 1C to speed up build efficiency

图片

after change：

图片

### CODE REVIEW

**Comment by JingsongLi** [comment]
Let's see if optimization is effective.

**Comment by zhuangchong** [comment]
No need to use `mvnw`.

the related pr: #1178

**Comment by MonsterChenzhuo** [comment]
> No need to use `mvnw`.
> 
> the related pr: #1178

Thanks for the reminder, I have removed mvnw

**Comment by MonsterChenzhuo** [comment]
@JingsongLi PTAL

**Comment by MonsterChenzhuo** [comment]
> Let's see if optimization is effective.

@JingsongLi PTAL,thanks.

A few minutes of optimization.Is this PR still worth merging?
图片

after change：

图片

**Review by JingsongLi — APPROVED** [review]
+1

This PR is not complicate.
And it looks like really improve a bit.
So I think it is worth to be merged.

**Pull request merged**
