### PR TITLE
[oss] use multi-release mechanism to ship jaxb

### LINKED ISSUE #2656: [Bug] could not find javax.xml.bind.JAXBException when use paimon oss plugin
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

release-0.6

### Compute Engine

flink

### Minimal reproduce step

image

### What doesn't meet your expectations?

jaxb-api should be included in the paimon oss plugin uber jar for java 9+， just like paimon-s3.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhoulii**
### Purpose

Linked issue: close #2656

### CODE REVIEW

**Comment by JingsongLi** [comment]
@zhoulii Please fix licensing issue.

**Comment by zhoulii** [comment]
> @zhoulii Please fix licensing issue.

Done and license check has passed.

**Comment by zhoulii** [comment]
Hi @Aitozi , could you please take a look at this PR? Thanks.

**Review by Aitozi — APPROVED** [review]
LGTM +1

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
