### PR TITLE
[core] Fix the issue of table copy

### LINKED ISSUE #2038: [Bug] failed to check filesystem
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

main branch

### Compute Engine

spark

### Minimal reproduce step

1. create table using `hive` and set `warehouse` to IP
2. read table using `spark` and set `warehouse` to hostname

### What doesn't meet your expectations?

```
java.lang.IllegalArgumentException: Wrong FS: hdfs://master-1-1:9000/user/hive/warehouse/paimon_test.db/hive_created_paimon_nopartition/snapshot, expected: hdfs://10.10.203.130:9000
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:730) ~[hadoop-client-api-3.2.1.jar:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:233) ~[hadoop-client-api-3.2.1.jar:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1576) ~[hadoop-client-api-3.2.1.jar:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1573) ~[hadoop-client-api-3.2.1.jar:?]
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-client-api-3.2.1.jar:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1588) ~[hadoop-client-api-3.2.1.jar:?]
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683) ~[hadoop-client-api-3.2.1.jar:?]
	at org.apache.paimon.fs.hadoop.HadoopFileIO.exists(HadoopFileIO.java:97) ~[paimon-spark-3.3-0.6-20230917.002123-11.jar:0.6-SNAPSHOT]
	at org.apache.paimon.utils.SnapshotManager.findLatest(SnapshotManager.java:298) ~[paimon-spark-3.3-0.6-20230917.002123-11.jar:0.6-SNAPSHOT]
	at org.apache.paimon.utils.SnapshotManager.latestSnapshotId(SnapshotManager.java:102) ~[paimon-spark-3.3-0.6-20230917.002123-11.jar:0.6-SNAPSHOT]
	at org.apache.paimon.table.source.snapshot.FullStartingScanner.<init>(FullStartingScanner.java:35) ~[paimon-spark-3.3-0.6-20230917.002123-11.jar:0.6-SNAPSHOT]
	at org.apache.paimon.table.source.AbstractInnerTableScan.createStartingScanner(AbstractInnerTableScan.java:112) ~[paimon-spark-3.3-0.6-20230917.002123-11.jar:0.6-SNAPSHOT]
	at org.apache.paimon.table.source.InnerTableScanImpl.plan(InnerTableScanImpl.java:57) ~[paimon-spark-3.3-0.6-20230917.002123-11.jar:0.6-SNAPSHOT]
	at org.apache.paimon.spark.SparkScan.splits(SparkScan.java:91) ~[paimon-spark-3.3-0.6-20230917.002123-11.jar:0.6-SNAPSHOT]
	at org.apache.paimon.spark.SparkScan$1.planInputPartitions(SparkScan.java:72) ~[paimon-spark-3.3-0.6-20230917.002123-11.jar:0.6-SNAPSHOT]
	at org.apache.spark.sql.execution.datasources.v2.BatchScanExec.inputPartitions$lzycompute(BatchScanExec.scala:54) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
	at org.apache.spark.sql.execution.datasources.v2.BatchScanExec.inputPartitions(BatchScanExec.scala:54) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
```

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by miomiocat**
Linked issue: close #2038

### CODE REVIEW

**Comment by SteNicholas** [comment]
@miomiocat, could you add test case to verify this bugfix?

**Comment by miomiocat** [comment]
> @miomiocat, could you add test case to verify this bugfix?

added, PTAL

**Comment by JingsongLi** [comment]
See test failed in: https://github.com/miomiocat/incubator-paimon/tree/fix_path

**Comment by miomiocat** [comment]
> See test failed in: https://github.com/miomiocat/incubator-paimon/tree/fix_path

Done. PTAL

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
