### PR TITLE
[CI] Add a GHA for adding labels based on modified files

### PR DESCRIPTION
**Pull request by jackwener**
*(Please specify the module before the PR name: [core] ... or [flink] ...)*

### Purpose

Add a GHA for adding labels based on modified files

### CODE REVIEW

**Review by JingsongLi — APPROVED** [review]
+1
thanks @jackwener

**Comment by JingsongLi** [comment]
reverted, this will result in PRs that do not pass the test and show a pattern ✅ that passes the test.

**Comment by jackwener** [comment]
> reverted, this will result in PRs that do not pass the test and show a pattern ✅ that passes the test.

Is there a example to see this condition? I can take a look it.

**Comment by jackwener** [comment]
I can't see the error log.
Just guess, If it failed due to this GitHub Action, it may be caused by Paimon don't have those `label`, we just need to add it.

**Pull request merged**
