### PR TITLE
[hive] Support timestamp and date type in hive3 for hive writer

### LINKED ISSUE #1368: [Bug] hive writer does not support timestamp and date type
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5-snapshot

### Compute Engine

hive

### Minimal reproduce step

insert into a paimon table contains timestamp type or date type

### What doesn't meet your expectations?

throw exception

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Alibaba-HZY**
### Purpose

Support timestamp and date type in hive3 for hive writer
Linked issue: close #1368

### Tests

HiveWriteITCase

### API and Format

no

### Documentation

no

### CODE REVIEW

**Comment by JingsongLi** [comment]
Test failed:
```
HiveWriteITCase.testInsertTimestampAndDate:221 expected:<[1	2023-01-13 20:00:01.123	2023-11-12]> but was:<[1	2023-01-13 20:00:01.123	2023-11-13]>
[INFO] 
```

**Comment by Alibaba-HZY** [comment]
> Test failed:
> 
> ```
> HiveWriteITCase.testInsertTimestampAndDate:221 expected:<[1	2023-01-13 20:00:01.123	2023-11-12]> but was:<[1	2023-01-13 20:00:01.123	2023-11-13]>
> [INFO] 
> ```



> Test failed:
> 
> ```
> HiveWriteITCase.testInsertTimestampAndDate:221 expected:<[1	2023-01-13 20:00:01.123	2023-11-12]> but was:<[1	2023-01-13 20:00:01.123	2023-11-13]>
> [INFO] 
> ```
The action seems to have passed?

**Comment by JingsongLi** [comment]
@Alibaba-HZY It is in your repo: https://github.com/Alibaba-HZY/incubator-paimon/actions/runs/5265567854/jobs/9518369679

**Comment by Alibaba-HZY** [comment]
> @Alibaba-HZY It is in your repo: https://github.com/Alibaba-HZY/incubator-paimon/actions/runs/5265567854/jobs/9518369679
> 
> Please check if there is unstable situation

fixed

**Comment by JingsongLi** [comment]
> > @Alibaba-HZY It is in your repo: https://github.com/Alibaba-HZY/incubator-paimon/actions/runs/5265567854/jobs/9518369679
> > Please check if there is unstable situation
> 
> fixed

Can you explain this? I cannot get why unstable.

**Comment by Alibaba-HZY** [comment]
> > > @Alibaba-HZY It is in your repo: https://github.com/Alibaba-HZY/incubator-paimon/actions/runs/5265567854/jobs/9518369679
> > > Please check if there is unstable situation
> > 
> > 
> > fixed
> 
> Can you explain this? I cannot get why unstable.

because in my repo 
image
timezone is gmt-4, before  i used org.apache.paimon.utils.DateTimeUtils#toInternal(java.sql.Date),it expression is   long ts = date.getTime() + LOCAL_TZ.getOffset(date.getTime());  this results in a day less than expected,so i use new method org.apache.paimon.utils.DateTimeUtils#toInternal(java.time.LocalDate)

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
