### PR TITLE
[flink] support big decimal for flink cdc sync action 

### PR DESCRIPTION
**Pull request by zhangjun0x01**
### Purpose

if the mysql has a decimal data like `2222222222222222300000001111.1234567890 ` ,when sync to paimon ,it is `2222222222222222400000000000.0000000000` , lose the precision.

### CODE REVIEW

**Comment by yuzelin** [comment]
Please rebase master. We have pushed some fix to solve the test timeout problem.

**Comment by zhangjun0x01** [comment]
> Please rebase master. We have pushed some fix to solve the test timeout problem.

done

**Comment by zhangjun0x01** [comment]
fix `MySqlCdcTypeMappingITCase#testReadAllTypes` method

**Review by yuzelin — APPROVED** [review]
+1

**Pull request merged**
