### PR TITLE
[core]Support Level Compaction

### PR DESCRIPTION
**Pull request by zhangjun0x01**
*(Please specify the module before the PR name: [core] ... or [flink] ...)*

### Purpose

*(provide level compaction, minimizes space amplification at the cost of read and write amplification.)*

### Tests

*(org.apache.paimon.mergetree.compact.LevelCompactionTest)*

### API and Format 

*(Does this change affect API or storage format)*

### Documentation

*(Does this change introduce a new feature)*

### CODE REVIEW

**Comment by wg1026688210** [comment]
hi~ @zhangjun0x01   ,the problem sonar reported has been resolved, you can rebase the master branch

**Comment by zhangjun0x01** [comment]
> hi~ @zhangjun0x01 ,the problem sonar reported has been resolved, you can rebase the master branch

thanks,I update it

**Comment by JingsongLi** [comment]
Why do we support level compaction? Is there any data result support on the benchmark?

**Comment by JingsongLi** [comment]
I prefer not to consider supporting it at the moment, as analytical systems such as clickhouse and even HBase do not have a good application of level compaction.

If you have more input, please let me know.

**Comment by zhangjun0x01** [comment]
> I prefer not to consider supporting it at the moment, as analytical systems such as clickhouse and even HBase do not have a good application of level compaction.
> 
> If you have more input, please let me know.

sorry for the late reply， my initial idea was，universal compaction use lower write amplification, trading off read amplification and space amplification. leveled compaction minimizes space amplification at the cost of read and write amplification. we should add multiple compaction styles so that users can choose based on their actual scenarios, just like other storage engines, such as Rocksdb and Cassandra

**Comment by JingsongLi** [comment]
Thank you for your explanation, we should write code based on the user's needs, if it is a requirement we set out on our own, we should do sufficient testing to prove our conjecture, there is a lack of evidence that this PR is useful for the user scenario.

**Comment by JingsongLi** [comment]
You can initiate a PIP if you have enough tests afterwards.

**Pull request closed without merging**
