### PR TITLE
[flink] fix exception related to field size after adding a new table

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
### Purpose

Fix the issue of throwing an exception related to field size after adding a new table.

### Tests

MongoDBSyncDatabaseActionITCase#testDynamicTableCreationInMongoDB()

### CODE REVIEW

**Review by JingsongLi — CHANGES_REQUESTED** [review]
Can you add a case to cover this fixing?

**Comment by MonsterChenzhuo** [comment]
> Can you add a case to cover this fixing?

没有问题，整整在

**Comment by JingsongLi** [comment]
@MonsterChenzhuo See `TestCaseInsensitiveCatalogFactory`.

**Comment by MonsterChenzhuo** [comment]
> @MonsterChenzhuo See `TestCaseInsensitiveCatalogFactory`.

@JingsongLi  PTAL,thanks.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
