### PR TITLE
[hive] Hive create table force db name and  table names to be lowercase

### PR DESCRIPTION
**Pull request by Alibaba-HZY**
### Purpose
Hive create table should force table names to be lowercase,consistent with hive behavior.
#1760 

### Tests

CreateTableITCase

### API and Format

no

### Documentation

no

### CODE REVIEW

**Review by zhuangchong — APPROVED** [review]
LGTM.

**Review by JingsongLi — CHANGES_REQUESTED** [review]
I just ran the tests in latest master. These two tests both passed.

Can you figure out what them test for?

**Comment by Alibaba-HZY** [comment]
> Thanks @Alibaba-HZY for the contribution.
> 
> I just ran the tests in latest master. These two tests both passed.
> 
> Can you figure out what them test for?

when i use

> Thanks @Alibaba-HZY for the contribution.
> 
> I just ran the tests in latest master. These two tests both passed.
> 
> Can you figure out what them test for?



> Thanks @Alibaba-HZY for the contribution.
> 
> I just ran the tests in latest master. These two tests both passed.
> 
> Can you figure out what them test for?

i have add assert table name by hive metastore path

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
