### PR TITLE
[hotfix] add column 'already exists' and 'does not exist' exception type

### LINKED ISSUE #900: [hotfix] add column `already exists` and `does not exist` exception type
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

At present, the columns `already exists` and `does not exist` abnormal printing information are as follows:

image

image

### Solution

add column `already exists` and `does not exist` exception type

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhuangchong**
*(Please specify the module before the PR name: [core] ... or [flink] ...)*

### Purpose

*(What is the purpose of the change, or the associated issue)*

This pr closes #900 

At present, the columns `already exists` and `does not exist` abnormal printing information are as follows:

image

image

Modified:

iShot_2023-04-13_17 23 20

iShot_2023-04-13_17 23 09

### Tests

*(List UT and IT cases to verify this change)*

### API and Format 

*(Does this change affect API or storage format)*

### Documentation

*(Does this change introduce a new feature)*

### CODE REVIEW

**Comment by SteNicholas** [comment]
@zhuangchong, could you rebase the master branch and squash into one commit? Don't merge the master branch.

**Comment by zhuangchong** [comment]
@tsreaper The execution of mysql cdc ci in this pr is abnormal, can you help me to see it? thanks.

https://github.com/apache/incubator-paimon/actions/runs/4698398274/jobs/8330630896?pr=902#step:5:564-572

**Comment by zhuangchong** [comment]
> @zhuangchong, could you rebase the master branch and squash into one commit? Don't merge the master branch.

Thanks. done.

**Review by JingsongLi — APPROVED** [review]
+1

**Comment by tsreaper** [comment]
This PR is not a valid solution because it assumes that each `tableRoot` in the `SchemaManager` stands for a table in a catalog. However we also support table outside of catalog (for example, `'connector' = 'paimon'` in Flink), also a lot of tests create `SchemaManager` with an arbitrary path which only holds a test table. These test tables also don't have catalogs and databases.

**Pull request merged**
