### PR TITLE
[spark] Add task metrics

### PR DESCRIPTION
**Pull request by YannByron**
### Purpose

without this:
image

with this:
image

### CODE REVIEW

**Review by JingsongLi — COMMENTED** [review]
Nice improvement.

Can we have UT case to test the metrics from Reader and the Paimon custom metrics?

**Comment by YannByron** [comment]
> Nice improvement.
> 
> Can we have UT case to test the metrics from Reader and the Paimon custom metrics?

hard to add some UTs for this.

**Review by JingsongLi — APPROVED** [review]
+1

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
