### PR TITLE
[cdc] Debezium-json supports debezium records with included schema

### PR DESCRIPTION
**Pull request by sunxiaojian**
### Purpose

Linked issue: close https://github.com/apache/incubator-paimon/issues/2227

###  Tests
org.apache.paimon.flink.action.cdc.kafka.KafkaDebeziumWithSchemaSyncTableActionITCase

### CODE REVIEW

**Comment by sunxiaojian** [comment]
@MonsterChenzhuo @yuzelin PTAL

**Comment by MonsterChenzhuo** [comment]
> @MonsterChenzhuo @yuzelin PTAL

ok.

**Comment by MonsterChenzhuo** [comment]
debezium will have several different situations, and I have made some definitions
The native of him is like this: 
debezium-native-avro 
debezium-native-json
The so-called native means that the primary key information of the table exists in the key of kafka.

The flinkcdc debezium format is like this:
debezium-exclude-json
debezium-include-json

**Comment by sunxiaojian** [comment]
> debezium will have several different situations, and I have made some definitions The native of him is like this: debezium-native-avro debezium-native-json -> #2261 The so-called native means that the primary key information of the table exists in the key of kafka.
> 
> The flinkcdc debezium format is like this: debezium-exclude-json debezium-include-json
> 
> Example： 图片



> debezium will have several different situations, and I have made some definitions The native of him is like this: debezium-native-avro debezium-native-json -> #2261 The so-called native means that the primary key information of the table exists in the key of kafka.
> 
> The flinkcdc debezium format is like this: debezium-exclude-json debezium-include-json
> 
> Example： 图片

1. I have submitted a PR in native mode for reference, https://github.com/apache/incubator-paimon/pull/2261
2. Debezium JSON should be handled with only one parser as much as possible, and the configuration should be consistent when using debezium JSON, such as flink-kafka-connector

**Comment by sunxiaojian** [comment]
> debezium will have several different situations, and I have made some definitions The native of him is like this: debezium-native-avro debezium-native-json -> #2261 The so-called native means that the primary key information of the table exists in the key of kafka.
> 
> The flinkcdc debezium format is like this: debezium-exclude-json debezium-include-json
> 
> Example： 图片

1. I have submitted a PR in native mode for reference, https://github.com/apache/incubator-paimon/pull/2261
2. Debezium JSON should be handled with only one parser as much as possible, and the configuration should be consistent when using debezium JSON, such as flink-kafka-connector

**Comment by MonsterChenzhuo** [comment]
> > debezium will have several different situations, and I have made some definitions The native of him is like this: debezium-native-avro debezium-native-json -> #2261 The so-called native means that the primary key information of the table exists in the key of kafka.
> > The flinkcdc debezium format is like this: debezium-exclude-json debezium-include-json
> > Example： 图片
> 
> @MonsterChenzhuo
> 
>     1. I have submitted a PR in native mode for reference, [[Feature] Add debezium-json format #2261](https://github.com/apache/incubator-paimon/pull/2261)
> 
>     2. Debezium JSON should be handled with only one parser as much as possible, and the configuration should be consistent when using debezium JSON, such as flink-kafka-connector

Flink cdc often does not store the primary key information of kafka.

**Comment by MonsterChenzhuo** [comment]
Format should cover the requirements of this part, because there are many users to kafak through flinkcdc dbz format.

**Comment by MonsterChenzhuo** [comment]
> 1. [[Feature] Add debezium-json format #2261](https://github.com/apache/incubator-paimon/pull/2261)

https://github.com/apache/incubator-paimon/pull/2261There is no problem with this pr.
But DataFormat needs to be changed.

> > > > debezium will have several different situations, and I have made some definitions The native of him is like this: debezium-native-avro debezium-native-json -> #2261 The so-called native means that the primary key information of the table exists in the key of kafka.
> > > > The flinkcdc debezium format is like this: debezium-exclude-json debezium-include-json
> > > > Example： 图片
> > > 
> > > 
> > > @MonsterChenzhuo
> > > ```
> > > 1. I have submitted a PR in native mode for reference, [[Feature] Add debezium-json format #2261](https://github.com/apache/incubator-paimon/pull/2261)
> > > 
> > > 2. Debezium JSON should be handled with only one parser as much as possible, and the configuration should be consistent when using debezium JSON, such as flink-kafka-connector
> > > ```
> > 
> > 
> > Flink cdc often does not store the primary key information of kafka. Format should cover the requirements of this part, because there are many users to kafak through flinkcdc dbz format.
> 
> I'm just saying to maintain consistent configuration, the deserialization method should still be defined by oneself
> 
> And don't break it down into "debezium-exclude-json" and ”debezium-include-json", just keep one debezium-json

+1

**Comment by yuzelin** [comment]
Resolve conflicts and remove JsonPrimaryKeyDeserializationSchema

**Review by JingsongLi — APPROVED** [review]
+1

**Comment by luckyLJY** [comment]
可以请教一下debezium json的配置项有哪些吗？目前我个人配置的json无法实现表结构的改变。

**Pull request merged**
