### PR TITLE
[Bug] fix first_row can not work with local merge operator

### LINKED ISSUE #2235: [Bug] Row serializer is not correct when local merge is enabled
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5.0

### Compute Engine

Flink

### Minimal reproduce step

```sql
        sql(
                "CREATE TABLE IF NOT EXISTS T1 ("
                        + "a INT, b INT, c STRING, PRIMARY KEY (a, b) NOT ENFORCED)"
                        + " PARTITIONED BY (b) WITH ('merge-engine'='first-row', 'local-merge-buffer-size' = '1m', 'file.format'='avro', 'changelog-producer' = 'lookup');");
        batchSql("INSERT INTO T1 VALUES (1, 1, '1'), (1, 1, '2'), (2, 3, '3')");
```

### What doesn't meet your expectations?

image

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Aitozi**
### Purpose

Linked issue: close #2235

### CODE REVIEW

**Comment by zhuangchong** [comment]
Run CI.

**Comment by Aitozi** [comment]
Hi, @zhuangchong The CI has passed at my [local branch]( https://github.com/Aitozi/incubator-paimon/actions?query=branch%3Alocal-merge++)

**Review by zhuangchong — APPROVED** [review]
+1

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
