### PR TITLE
[core] New parameters `commit.force-create-snapshot` Used to force a snapshot to be generated when committing

### LINKED ISSUE #2957: [Feature] Make `forceCreatingSnapshot` a toggle option for paimon
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

PaimonSink Commit has a logic that if no data is written during a checkpoint cycle, no snapshot will be generated.
Let me give you an example:

If I read a kafka stream and write it to Paimon, there may be filters in the middle, and flink watermarks are generated at the same time. Then each snapshot of Paimon will have watermark information. I can judge my writing progress through the watermark of the latest snapshot. , if the watermark is advancing in a checkpoint interval, but the filter logic filters out the data, a snapshot will not be generated, but the watermark should be advancing.

Currently, forced snapshot generation only takes effect when the automatic tag creation configuration is enabled and certain conditions are met. I think we should make this a switchable option.

### Solution

Make `forceCreatingSnapshot` a toggle option for paimon

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by huyuanfeng2018**
### Purpose

Linked issue: close #2957

### Tests

`org.apache.paimon.flink.sink.CommitterOperatorTest#testForceCreateSnapshotCommit`

### CODE REVIEW

**Comment by huyuanfeng2018** [comment]
@JingsongLi PTAL. 

thanks.

**Comment by JingsongLi** [comment]
@huyuanfeng2018  Take a look to `paimon-docs/README`.

**Comment by huyuanfeng2018** [comment]
> @huyuanfeng2018 Take a look to `paimon-docs/README`.

done.

**Review by JingsongLi — APPROVED** [review]
+1 Thanks @huyuanfeng2018

**Pull request merged**
