### PR TITLE
[test] add wait time for runnable in thread pool

### PR DESCRIPTION
**Pull request by leaves12138**
Add wait time for runnable in thread pool, the last runnable may not be stopped by shutdown.

### CODE REVIEW

**Comment by JingsongLi** [comment]
Thanks @leaves12138 for your contribution.

But can you explain what is the problem?

> the last runnable may not be stopped by shutdown.

So what?

**Comment by leaves12138** [comment]
> Thanks @leaves12138 for your contribution.
> 
> But can you explain what is the problem?
> 
> > the last runnable may not be stopped by shutdown.
> 
> So what?

When executorPool called shutdown, maybe there is a runnable thread in thread pool, and have not get some place to handle InterruptedException. Then it will still hold the open output stream. The method `TableTestBase.after` will check if all the output streams are closed. It will throw an assert exception.

**Comment by JingsongLi** [comment]
> > Thanks @leaves12138 for your contribution.
> > But can you explain what is the problem?
> > > the last runnable may not be stopped by shutdown.
> > 
> > 
> > So what?
> 
> When executorPool called shutdown, maybe there is a runnable thread in thread pool, and have not get some place to handle InterruptedException. Then it will still hold the open output stream. The method `TableTestBase.after` will check if all the output streams are closed. It will throw an assert exception.

I still cannot get it. Are there some cases fail?

**Comment by leaves12138** [comment]
> > > Thanks @leaves12138 for your contribution.
> > > But can you explain what is the problem?
> > > > the last runnable may not be stopped by shutdown.
> > > 
> > > 
> > > So what?
> > 
> > 
> > When executorPool called shutdown, maybe there is a runnable thread in thread pool, and have not get some place to handle InterruptedException. Then it will still hold the open output stream. The method `TableTestBase.after` will check if all the output streams are closed. It will throw an assert exception.
> 
> I still cannot get it. Are there some cases fail?

occasionally, 
image
This may throws en error, because there is still one thread running in thread pool occupied an output stream or input stream

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
