### PR TITLE
[Feature] Supports Rabbitmq CDC

### LINKED ISSUE #2322: [Feature] Supports Rabbitmq CDC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Supports Rabbitmq CDC ingestion

### Solution

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by sunxiaojian**
### Purpose

Linked issue: close #2322

### CODE REVIEW

**Comment by JingsongLi** [comment]
Is this what users (or your company?) need? Because I rarely hear about the combination of Rabbitmq and Flink.

**Comment by sunxiaojian** [comment]
> Is this what users (or your company?) need? Because I rarely hear about the combination of Rabbitmq and Flink.

yes，It is indeed rarely used.

**Comment by JingsongLi** [comment]
OK, there is no plan to support Rabbitmq now. I will close this, feel free to re-open if you think this is needed.

**Comment by sunxiaojian** [comment]
> OK, there is no plan to support Rabbitmq now. I will close this, feel free to re-open if you think this is needed.

ok

**Pull request closed without merging**
