### PR TITLE
[cdc] CDC schema evolution supports all type conversions already supported by paimon

### LINKED ISSUE #2080: [Feature] CDC schema evolution supports all type conversions already supported by paimon
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

CDC schema evolution supports all type conversions already supported by paimon

paimon supported type conversions:
https://paimon.apache.org/docs/master/how-to/altering-tables/#changing-column-type

### Solution

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhuangchong**
### Purpose

Linked issue: close #2080

### CODE REVIEW

**Review by JingsongLi — CHANGES_REQUESTED** [review]
All type conversions may result blocking, if there is casting failure.

**Comment by zhuangchong** [comment]
> All type conversions may result blocking, if there is casting failure.

Thanks. @JingsongLi 

I found that if the data conversion fails in the cdc sink operator, it will perform cyclic conversion processing, which will eventually lead to blocking. 

What do you think if this abnormal data is printed and filtered when the conversion fails?

**Comment by JingsongLi** [comment]
> > All type conversions may result blocking, if there is casting failure.
> 
> Thanks. @JingsongLi
> 
> I found that if the data conversion fails in the cdc sink operator, it will perform cyclic conversion processing, which will eventually lead to blocking.
> 
> What do you think if this abnormal data is printed and filtered when the conversion fails?

We should not just throw abnormal data because of distributed processing.

So for our CDC, we don't support all type conversions.

**Comment by zhuangchong** [comment]
> So for our CDC, we don't support all type conversions.

Explicit conversion may cause data conversion to fail, CDC can only support implicit conversion. This allows CDC schema changes to be supported more richly than before.

https://github.com/apache/incubator-paimon/blob/3abccb832a8bd9390c24a9d8ab61fa570750d84b/paimon-common/src/main/java/org/apache/paimon/types/DataTypeCasts.java#L180-L202

**Comment by JingsongLi** [comment]
Not just implicit conversion.
Consider varchar(10) -> varchar(2) -> varchar(10). This is an implicit conversion, but is NOT OK for our CDC. The data may be lost because of varchar(2).

**Comment by zhuangchong** [comment]
@JingsongLi Thanks. 

I didn't consider it comprehensively, so I will close this PR.

**Pull request closed without merging**
