### PR TITLE
[ci] Build strategy matrix using multiple java environments in the CI

### LINKED ISSUE #799: [Feature] Build strategy matrix using multiple java environments in the CI
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Build strategy matrix using multiple java environments in the CI

### Solution

Build strategy matrix using multiple java environments in the CI

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhuangchong**
*(Please specify the module before the PR name: [core] ... or [flink] ...)*

### Purpose

*(What is the purpose of the change, or the associated issue)*
this pr closes #799 

### Tests

*(List UT and IT cases to verify this change)*

### API and Format 

*(Does this change affect API or storage format)*

### Documentation

*(Does this change introduce a new feature)*

### CODE REVIEW

**Comment by zhuangchong** [comment]
I recommend that each PR run CI checks for both JDK8 and JDK11.

**Comment by JingsongLi** [comment]
Please take a look to the discussion in https://github.com/apache/incubator-paimon/pull/714

**Comment by JingsongLi** [comment]
Hi @zhuangchong , maybe we can add a few jdk 11 tests in future.
But not now, our testing is still unstable and time-consuming. Consume my energy.

**Comment by zhuangchong** [comment]
> Hi @zhuangchong , maybe we can add a few jdk 11 tests in future. But not now, our testing is still unstable and time-consuming. Consume my energy.

OK, Thanks for your comments.

**Pull request closed without merging**
