### PR TITLE
[flink] auto create new tag for flink savepoint.

### LINKED ISSUE #1635: [Feature] Create new tag for flink savepoint
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently Paimon supports tag to store data which can be associated with flink savepoint. When Flink perform a savepoint on sink operator, it can create a tag automatically after create a snapshot.

### Solution

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by liming30**
### Purpose

Linked issue: close #1635 

Auto create new tag for flink savepoint.

### Tests

Add `org.apache.paimon.flink.sink.AutoTagForSavepointCommitterOperatorTest` to verify correctness.

- `org.apache.paimon.flink.sink.AutoTagForSavepointCommitterOperatorTest#testAutoTagForSavepoint`
- `org.apache.paimon.flink.sink.AutoTagForSavepointCommitterOperatorTest#testRestore`

### API and Format

No
### Documentation

No

### CODE REVIEW

**Comment by JingsongLi** [comment]
I left comment in issue and want to figure out why we need this feature.

**Review by JingsongLi — COMMENTED** [review]
The changes looks good to me.

We should add some document for this. Explain how to use this feature.

**Comment by liming30** [comment]
@JingsongLi Added documentation to introduce this feature, please help to review it when you have time.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
