### PR TITLE
[Feature] Add debezium-json format

### PR DESCRIPTION
**Pull request by sunxiaojian**
### Purpose

Linked issue: close [#2227](https://github.com/apache/incubator-paimon/issues/2227)
Add debezium-json format

### CODE REVIEW

**Comment by sunxiaojian** [comment]
@JingsongLi PTAL

**Comment by sunxiaojian** [comment]
@MonsterChenzhuo @yuzelin Could you please take a look and see if this PR is still retained? If so, I will handle the conflict

**Comment by MonsterChenzhuo** [comment]
处理下冲突吧

> @MonsterChenzhuo @yuzelin Could you please take a look and see if this PR is still retained? If so, I will handle the conflict

Deal with the conflict.

**Comment by sunxiaojian** [comment]
> Deal with the conflict.

ok

**Comment by sunxiaojian** [comment]
> > @MonsterChenzhuo @yuzelin Could you please take a look and see if this PR is still retained? If so, I will handle the conflict
> 
> Deal with the conflict.

done

**Comment by sunxiaojian** [comment]
> > @MonsterChenzhuo @yuzelin Could you please take a look and see if this PR is still retained? If so, I will handle the conflict
> 
> Deal with the conflict.

@MonsterChenzhuo PTAL

**Comment by JingsongLi** [comment]
I see #2251 has been merged, what is the relationship?

**Comment by sunxiaojian** [comment]
> I see #2251 has been merged, what is the relationship?

https://github.com/apache/incubator-paimon/pull/2280 PTAL   @JingsongLi

**Pull request closed without merging**
