### PR TITLE
[flink] Introduce dbz cdc dataType

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
### Purpose

Introduce dbz cdc dataType.

### CODE REVIEW

**Review by yuzelin — APPROVED** [review]
+1

**Comment by TaoZex** [comment]
Add doc for users may be better. @MonsterChenzhuo

**Comment by yuzelin** [comment]
> Add doc for users may be better. @MonsterChenzhuo

You're right. I'm considering to do some refactor. I will add docs then.

**Comment by TaoZex** [comment]
> > Add doc for users may be better. @MonsterChenzhuo
> 
> You're right. I'm considering to do some refactor. I will add docs then.

Look forward to this work.

**Pull request merged**
