### PR TITLE
[common] Use caffeine to replace with guava cache

### LINKED ISSUE #636: [feature] Use caffeine to replace with guava cache
the performance of caffeine is better.

### PR DESCRIPTION
**Pull request by zhuangchong**
*(Please specify the module before the PR name: [core] ... or [flink] ...)*

### Purpose

*(What is the purpose of the change, or the associated issue)*
this pr closes #636 

### Tests

*(List UT and IT cases to verify this change)*

### API and Format 

*(Does this change affect API or storage format)*

### Documentation

*(Does this change introduce a new feature)*

### CODE REVIEW

**Comment by JingsongLi** [comment]
Maybe we need to release relocated caffiene in https://github.com/apache/incubator-paimon-shade first.

**Comment by JingsongLi** [comment]
Currently, paimon-shade releasing is blocked by https://issues.apache.org/jira/browse/INFRA-24372

**Comment by JingsongLi** [comment]
we already have shaded caffiene dependency, you can continue to finish this.

**Comment by zhuangchong** [comment]
> we already have shaded caffiene dependency, you can continue to finish this.

Thanks. done.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
