### PR TITLE
[spark] Extract SparkInputPartitionReader from paimon spark connector

### PR DESCRIPTION
**Pull request by TyrantLucifer**
Extract SparkInputPartitionReader from paimon spark connector

### Purpose

Optimize code structure

### Tests

*(List UT and IT cases to verify this change)*

### API and Format 

*(Does this change affect API or storage format)*

### Documentation

*(Does this change introduce a new feature)*

### CODE REVIEW

**Comment by JingsongLi** [comment]
Hi @TyrantLucifer , thanks for your contribution, can you explain the disadvantages of anonymous internal classes?

**Comment by TyrantLucifer** [comment]
> Hi @TyrantLucifer , thanks for your contribution, can you explain the disadvantages of anonymous internal classes?

Thank you for your reply. There are two benefits to converting an internal anonymous class to a regular entity class:

1. Improved code readability and maintainability: Using an explicit entity class with a well-defined name and a clear purpose makes it easier for other developers to understand the code's purpose and functionality. This can also make it easier to maintain the code over time.

2. Enhanced code reusability: By separating the anonymous class into a separate entity class, the class can be reused in other parts of the codebase, potentially reducing code duplication and improving overall code quality.

Of course, from a performance perspective, there is no difference between the two approaches.

What do you think about it?

**Comment by JingsongLi** [comment]
> 2\. t

Thanks for your reply and explanation. I will merge this. But this is not a bad mark for an anonymous internal class, and we would not recommend not using anonymous internal classes.
I think in most moments it's just a matter of personal preference.

**Comment by TyrantLucifer** [comment]
> > 2. t
> 
> Thanks for your reply and explanation. I will merge this. But this is not a bad mark for an anonymous internal class, and we would not recommend not using anonymous internal classes. I think in most moments it's just a matter of personal preference.

Thank you for your good advice. I will avoid this problem in the future and try to contribute other useful codes.:wink:

**Pull request merged**
