### PR TITLE
[CI] Solve the problem of starting multiple actions at the same time

### PR DESCRIPTION
**Pull request by liugddx**
*(Please specify the module before the PR name: [core] ... or [flink] ...)*

### Purpose

 Solve the problem of starting multiple actions at the same time.

### Tests

*(List UT and IT cases to verify this change)*

### API and Format 

*(Does this change affect API or storage format)*

### Documentation

*(Does this change introduce a new feature)*

### CODE REVIEW

**Comment by liugddx** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobs

**Comment by liugddx** [comment]
> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobs

I operated it and found that it didn't take more time than before to start the jdk11 test, and github supports running jobs in parallel

**Comment by liugddx** [comment]
image

It is work.

**Review by JingsongLi — APPROVED** [review]
Looks good to me!

**Pull request merged**
