### PR TITLE
[core]filesystems huawei obs implements

### LINKED ISSUE #2335: [Feature] implement huawei obs file system
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

If I work on huaweicloud, I need use huawei obs file system to store the files.

### Solution

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by littlefisher666**
### Purpose

Linked issue: close #2335

### CODE REVIEW

**Comment by JingsongLi** [comment]
Can you explain what difference between OBS API and S3 API for OBS?

**Comment by littlefisher666** [comment]
> Can you explain what difference between OBS API and S3 API for OBS?

There isn't much difference between OBS API and OSS API. But I don't know what difference between OBS API and S3 API.
OBS和OSS的API其实并没有太大的区别，只不过我不太清楚OBS和S3的差异

It is all rely on hadoop connector but use different sdk which is developed by different company.
OBS和OSS的API都是依赖于Hadoop连接器，只不过是不同的公司所开发的sdk罢了

**Comment by JingsongLi** [comment]
If no difference, we can just use S3 API to access OBS？

**Comment by littlefisher666** [comment]
> If no difference, we can just use S3 API to access OBS？

OBS uses different sdk, so it cannot use S3 API or OSS API. Please read the paimon-obs-impl/pom.xml, It rely on OBS sdk.
OBS使用了不同的sdk，所以不能够使用S3 或者OSS的API。请看下paimon-obs-impl/pom.xml，它依赖了OBS专用的sdk。

```
<groupId>com.huaweicloud.obs</groupId>
<artifactId>hadoop-huaweicloud</artifactId>
<version>${hadoop-huaweicloud.version}</version>
```

**Comment by JingsongLi** [comment]
I just mean: use paimon-s3 to access OBS.

**Comment by littlefisher666** [comment]
> I just mean: use paimon-s3 to access OBS.

Is there any example for using paimon-s3 to access aliyun OSS? Because OBS is like aliyun OSS. If I can use S3 to access OSS, I can also use S3 to access OBS.

**Comment by JingsongLi** [comment]
You can baidu: https://blog.csdn.net/weixin_39132936/article/details/103260024

**Comment by littlefisher666** [comment]
> You can baidu: https://blog.csdn.net/weixin_39132936/article/details/103260024

I tried and it can be use to access huaweicloud OBS. 

Thank you.

**Pull request closed without merging**
