### PR TITLE
[Document] Add document for hdfs and recommend to use the computing engine's own filesystem

### LINKED ISSUE #664: [Document] Add document for hdfs and recommend to use the computing engine's own filesystem
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

- Add doc for hdfs
- recommend to use the computing engine's own filesystem, like flink with own fs, spark with hadoop fs, hive with hadoop fs.

### Solution

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by liugddx**
close #664 

### Documentation

Add document for hdfs and recommend to use the computing engine's own filesystem

### CODE REVIEW

**Comment by JingsongLi** [comment]
https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/deployment/filesystems/overview/#hadoop-file-system-hdfs-and-its-other-implementations

Also can support Alluxio like Flink.

**Comment by JingsongLi** [comment]
Also document `HadoopUtils`.

**Comment by liugddx** [comment]
> Also document `HadoopUtils`.

Sorry, I'm still familiar with paimon, can you tell me more about this?

**Comment by JingsongLi** [comment]
> > Also document `HadoopUtils`.
> 
> Sorry, I'm still familiar with paimon, can you tell me more about this?

Sorry, it is hard to explain, otherwise, I'll just write the documentation.
The key point is that you haven't tried these features.
Can you just try to contribute something else? Maybe some bugs to fix.

**Comment by liugddx** [comment]
> > > Also document `HadoopUtils`.
> > 
> > 
> > Sorry, I'm still familiar with paimon, can you tell me more about this?
> 
> Sorry, it is hard to explain, otherwise, I'll just write the documentation. The key point is that you haven't tried these features. Can you just try to contribute something else? Maybe some bugs to fix.

Ok, thanks for the reply. I will close this pr.

**Comment by JingsongLi** [comment]
> > > > Also document `HadoopUtils`.
> > > 
> > > 
> > > Sorry, I'm still familiar with paimon, can you tell me more about this?
> > 
> > 
> > Sorry, it is hard to explain, otherwise, I'll just write the documentation. The key point is that you haven't tried these features. Can you just try to contribute something else? Maybe some bugs to fix.
> 
> Ok, thanks for the reply. I will close this pr.

Thanks!

**Pull request closed without merging**
