### PR TITLE
[Spark]Spark sql support get/list function

### PR DESCRIPTION
**Pull request by waywtdcc**
Spark sql support get/list function

### CODE REVIEW

**Comment by JingsongLi** [comment]
CC @YannByron

**Comment by YannByron** [comment]
LGTM. @waywtdcc please rebase master and fix the spotless style.

**Comment by waywtdcc** [comment]
> LGTM. @waywtdcc please rebase master and fix the spotless style.

ok

**Comment by JingsongLi** [comment]
+1

**Pull request merged**
