### PR TITLE
[hive] Use new ReadBuilder and WriteBuilder API in tests of paimon-hive module

### PR DESCRIPTION
**Pull request by TyrantLucifer**
Use new ReadBuilder and WriteBuilder API in tests of paimon-hive module

sub-task of #639

### CODE REVIEW

**Review by tsreaper — COMMENTED** [review]
Please also delete the `commitUser` class member of these two test classes.

**Comment by TyrantLucifer** [comment]
> Please also delete the `commitUser` class member of these two test classes.

Thank you for you reply, I will fix this problem later.

**Comment by TyrantLucifer** [comment]
> Thanks @TyrantLucifer for the contribution.
> 
> 
> 
> Can we make `FileStoreTestUtils.createFileStoreTable` returning `Table`?
> 
> And we can use `Catalog` to return `Table` too.

Thank you for your advice，I will change it later.

**Comment by TyrantLucifer** [comment]
> Thanks @TyrantLucifer for the contribution.
> 
> Can we make `FileStoreTestUtils.createFileStoreTable` returning `Table`? And we can use `Catalog` to return `Table` too.

Hi @JingsongLi , I have already finished this task, PTAL. :wink:

**Review by JingsongLi — APPROVED** [review]
Thanks @TyrantLucifer ! Looks good to me!

**Pull request merged**
