### PR TITLE
[spark]Fix spark write commit.force-compact parameter does not take effect

### PR DESCRIPTION
**Pull request by waywtdcc**
### Purpose
[spark]Fix spark write commit.force-compact parameter does not take effect

### CODE REVIEW

**Comment by JingsongLi** [comment]
Hi @waywtdcc .
We don't force full-compaction for every Spark write job.

**Comment by JingsongLi** [comment]
You can re-open this if you have question.

**Comment by waywtdcc** [comment]
> Hi @waywtdcc . We don't force full-compaction for every Spark write job.

What is the significance of setting commit.force-compact in spark?

**Comment by zhongtiancai** [comment]
> What is the significance of setting commit.force-compact in spark?
I have the same doubts  in flink, This options appears to only wait for the last compaction to complete. @JingsongLi

**Pull request closed without merging**
