### PR TITLE
[flink] [fix] Flink add computed column should be nullable

### PR DESCRIPTION
**Pull request by leaves12138**
### Purpose

sql "ALTER TABLE T add (__proc_time AS PROCTIME())" should be work well with paimon. And the clumn __proc_time which is ComputedColumn should be nullable.

### CODE REVIEW

**Comment by JingsongLi** [comment]
You should add test to use computed column and watermark for reading.

**Comment by leaves12138** [comment]
> You should add test to use computed column and watermark for reading, a real ITCase.

done

**Comment by JingsongLi** [comment]
@leaves12138 Maybe you can just take a review to #2297, is that what you want?

**Comment by leaves12138** [comment]
Already resolved in https://github.com/apache/incubator-paimon/pull/2297#pullrequestreview-1728717978

**Pull request closed without merging**
