### PR TITLE
[filesystems] Support huawei cloud OBS

### LINKED ISSUE #1042: [Feature][FileSystem] Support huawei cloud OBS
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Paimon support huawei cloud  obs fileSystem.

### Solution

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by kim-up**
[paimon-filesystens]

### Purpose

FIx #1042

#### create catalog useing obs file system.

image

#### use catalog and create a word count table, and create a word data generator table
image

#### write stream data to dynamic table
image

#### query data 
image

image

#### Files in OBS 
image

### API and Format 

*(Does this change affect API or storage format)*

### Documentation

docs/content/filesystems/obs.md

### CODE REVIEW

**Comment by JingsongLi** [comment]
Thanks @kim-up for the contribution.
License check failed in : https://github.com/kim-up/incubator-paimon/actions

**Comment by JingsongLi** [comment]
Just to confirm, huawei cloud OBS doesn't have S3 compatibility, right?

**Comment by kim-up** [comment]
> Just to confirm, huawei cloud OBS doesn't have S3 compatibility, right?

S3 is compatible with OBS.

**Comment by kim-up** [comment]
> > Just to confirm, huawei cloud OBS doesn't have S3 compatibility, right?
> 
> OBS is compatible with S3.

@JingsongLi So, there is no need to support obs ？

**Comment by JingsongLi** [comment]
> > > Just to confirm, huawei cloud OBS doesn't have S3 compatibility, right?
> > 
> > 
> > OBS is compatible with S3.
> 
> @JingsongLi So, there is no need to support obs ？

Is there a benefit to us going to direct support obs mainly? than the way accessing S3 API.

**Comment by kim-up** [comment]
> > > > Just to confirm, huawei cloud OBS doesn't have S3 compatibility, right?
> > > 
> > > 
> > > OBS is compatible with S3.
> > 
> > 
> > @JingsongLi So, there is no need to support obs ？
> 
> Is there a benefit to us going to direct support obs mainly? than the way accessing S3 API.

At present, it seems that there is no difference for users, so I will close this PR.

**Pull request closed without merging**
