### PR TITLE
[ci] Add CI for Flink CDC test running on JDK11

### LINKED ISSUE #2005: [CI] Added CI for Flink CDC test running on JDK11
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Added CI for Flink CDC test running on JDK11

### Solution

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Jake-00**
### Purpose
Add CI step for Flink CDC test running on JDK11, and modify CI file name for Flink CDC test running on JDK8.

Linked issue: close #2005

### CODE REVIEW

**Comment by Jake-00** [comment]
@ZhangChaoming plz help to cr this pr when free, thx

**Comment by zhuangchong** [comment]
The original file name does not need to be changed. Please keep it consistent with other ci file name formats.

**Comment by Jake-00** [comment]
> The original file name does not need to be changed. Please keep it consistent with other ci file name formats.

The original ci file name is back.

**Review by zhuangchong — APPROVED** [review]
+1

**Pull request merged**
