### PR TITLE
[flink]Improve get kafka schema

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
### Purpose

The current configuration for retry attempts and retry intervals seems inappropriate: the number of retry attempts is set at 100, and the retry interval is set at 100 milliseconds. It is suggested to adjust these values to a more reasonable setting, such as 5 retry attempts and a retry interval of 1000 milliseconds. Additionally, implementing an exponential backoff strategy would be beneficial, which progressively increases the retry waiting time with each attempt.

### CODE REVIEW

**Comment by MonsterChenzhuo** [comment]
@JingsongLi  PTAL,thanks.

**Comment by JingsongLi** [comment]
> It is not ideal that the KafkaSchema#getKafkaSchema() method could potentially execute the new CanalRecordParser operation without checking if records are available first. It is recommended to include a check for the presence of records before performing the new CanalRecordParser operation.

I cannot get it. What do you mean?

**Comment by MonsterChenzhuo** [comment]
> > It is not ideal that the KafkaSchema#getKafkaSchema() method could potentially execute the new CanalRecordParser operation without checking if records are available first. It is recommended to include a check for the presence of records before performing the new CanalRecordParser operation.
> 
> I cannot get it. What do you mean?
If records is null, the process will proceed to create a new CanalRecordParser. What I mean is, before creating a new CanalRecordParser, there should be a check to ensure that records is not empty.
图片

**Comment by MonsterChenzhuo** [comment]
> > It is not ideal that the KafkaSchema#getKafkaSchema() method could potentially execute the new CanalRecordParser operation without checking if records are available first. It is recommended to include a check for the presence of records before performing the new CanalRecordParser operation.
> 
> I cannot get it. What do you mean?

This passage was written incorrectly, and I have already deleted it. Please disregard it.

**Comment by JingsongLi** [comment]
@MonsterChenzhuo So you can revert changes, and just modify sleep time?

**Comment by MonsterChenzhuo** [comment]
> @MonsterChenzhuo So you can revert changes, and just modify sleep time?

Yeah

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
