### PR TITLE
[spark] Fix call procedure compatibility with spark3.2

### PR DESCRIPTION
**Pull request by Zouxxyy**
### Purpose

Linked issue: close #xxx

### CODE REVIEW

**Comment by Zouxxyy** [comment]
@YannByron

**Comment by JingsongLi** [comment]
@Zouxxyy Does this bug also in 0.6 too?

**Comment by Zouxxyy** [comment]
> @Zouxxyy Does this bug also in 0.6 too?

Yes

**Comment by JingsongLi** [comment]
@YannByron Do you think this is a blocker for 0.6.1?

**Comment by YannByron** [comment]
> @YannByron Do you think this is a blocker for 0.6.1?

Yes. It can be cherry-picked to 0.6.1.

**Comment by YannByron** [comment]
+1. Mergiing.

**Pull request merged**
