### PR TITLE
[flink] Introduce FlinkGenericCatalog

### PR DESCRIPTION
**Pull request by JingsongLi**
### Purpose

Using FlinkGenericCatalog, you need to use Hive metastore. Then, you can use all the tables from Paimon, Hive, and
Flink Generic Tables (Kafka and other tables)!

In this mode, you should use 'connector' option for creating tables.

```sql
CREATE CATALOG my_catalog WITH (
    'type'='paimon-generic',
    'hive-conf-dir'='...',
    'hadoop-conf-dir'='...'
);

USE CATALOG my_catalog;

-- create a word count table
CREATE TABLE word_count (
    word STRING PRIMARY KEY NOT ENFORCED,
    cnt BIGINT
) WITH (
    'connector'='paimon'
);
```

### CODE REVIEW

**Comment by hdygxsj** [comment]
Do we have to use hive metastore? Why not consider persisting to paimon's own file system

**Review by yuzelin — APPROVED** [review]
+1

**Review by SteNicholas — APPROVED** [review]
LGTM.

**Review by zhuangchong — APPROVED** [review]
+1

**Comment by JingsongLi** [comment]
> Do we have to use hive metastore? Why not consider persisting to paimon's own file system

Hi @hdygxsj , I replied you in https://github.com/apache/incubator-paimon/issues/1804 , please take a look~

**Pull request merged**
