### PR TITLE
[benchmark] benchmark module code optimization 

### PR DESCRIPTION
**Pull request by ChengJie1053**
1. `host` is of type string, replacing `Objects.equals` with `StringUtils.equals`
2. `CollectionUtils.isEmpty` replaces `List.isEmpty`
3. Removes excess `ExecutionException`
4. Extract the `closeReader`
5. Extract `all` as a constant

### CODE REVIEW

**Review by JingsongLi — COMMENTED** [review]
Thanks @ChengJie1053 for the contribution.

But most of optimizations are not required.

**Comment by JingsongLi** [comment]
Can you just keep
3. Removes excess ExecutionException
4. Extract the closeReader

**Comment by ChengJie1053** [comment]
> Can you just keep
> 3. Removes excess ExecutionException
> 4. Extract the closeReader

Ok, thanks for reviewing the code

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
