### PR TITLE
[test] Enable JUnit 5 Automatic Extension Detection

### PR DESCRIPTION
**Pull request by reswqa**
### Purpose

We can use Junit5's `SPI` mechanism to automatically introduce `TestLoggerExtension`.

### Tests

*Manually verified.*

### API and Format

*No change.*

### Documentation

*No need.*

### CODE REVIEW

**Comment by reswqa** [comment]
Hi @yuzelin, would you mind taking a look at this? Thanks!

**Review by JingsongLi — COMMENTED** [review]
I am not a expert of junit5... Why to modify the version of maven-surefire-plugin?

**Comment by reswqa** [comment]
Thanks for the reply! 

> Why to modify the version of maven-surefire-plugin?
As mentioned in the first commit message: maven surefire version `3.x` provides better support regarding the `JUnit Platform`. Otherwise, Junt5 related configurations such as `<junit.jupiter.extensions.autodetection.enabled>` will not take effect. BTW, flink has also updated its version to `3.x` for this reason.

**Comment by JingsongLi** [comment]
> Thanks for the reply @JingsongLi !
> 
> > Why to modify the version of maven-surefire-plugin?
> 
> As mentioned in the first commit message: maven surefire version `3.x` provides better support regarding the `JUnit Platform`. Otherwise, Junt5 related configurations such as `<junit.jupiter.extensions.autodetection.enabled>` will not take effect. BTW, flink has also updated its version to `3.x` for this reason.

Thanks for the explanation, can you also mention the PR in Flink?

**Comment by reswqa** [comment]
https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven

**Comment by reswqa** [comment]
Junit5's [doc](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven) recommended to use version `3.0.0-M4` or later to avoid interoperability issues. I have also tested `2.22.1(The version we are currently using)`, which supports running junit5 tests but does not support `junit.jupiter.extensions.autodetection.enabled`.

> BTW, flink has also updated its version to 3.x for this reason.

Correction: I made a mistake here, flink updated the version of `maven-surefire-plugin` to resolve `Corrupted STDOUT` issues(FLINK-24983), not to support `Junit5`.

> can you also link the PR in Flink?
But it also enables JUnit 5 automatic extension detection(FLINK-26218). to avoid mark too many test classes with `TestLoggerExtension`.

**Review by JingsongLi — APPROVED** [review]
Thanks @reswqa ! Looks good to me!

**Pull request merged**
